<a href="https://colab.research.google.com/github/Teolinlesp/desafio3PythonTelecom-X-Parte2/blob/main/Desafio3TelecomParte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠️ Preparación de los Datos

## Extracción del Archivo Tratado Parte 1

In [ ]:
import pandas as pd
datosTelecom2 = pd.read_csv("datos_tratados.csv")
datosTelecom2.head()

,ID_Cliente,Abandono,Género,Adulto_Mayor,Pareja,Dependientes,Antigüedad_Meses,Teléfono_Servicio,Teléfono_Múltiples_Líneas,Internet_Tipo_Servicio,...,Internet_Protección_Dispositivo,Internet_Soporte_Técnico,Internet_TV_Streaming,Internet_Películas_Streaming,Cuenta_Tipo_Contrato,Cuenta_Facturación_Sin_Papel,Cuenta_Método_Pago,Cuenta_Cargo_Mensual,Cuenta_Cargo_Total,Cuentas_Diarias
0,0002-orfbo,0.0,female,0,1,1,9,1,0.0,dsl,...,0.0,1.0,1.0,0.0,one year,1,mailed check,65.6,593.30,2.186667
1,0003-mknfe,0.0,male,0,0,0,9,1,1.0,dsl,...,0.0,0.0,0.0,1.0,month-to-month,0,mailed check,59.9,542.40,1.996667
2,0004-tlhlj,1.0,male,0,0,0,4,1,0.0,fiber optic,...,1.0,0.0,0.0,0.0,month-to-month,1,electronic check,73.9,280.85,2.463333
3,0011-igkff,1.0,male,1,1,0,13,1,0.0,fiber optic,...,1.0,0.0,1.0,1.0,month-to-month,1,electronic check,98.0,1237.85,3.266667
4,0013-exchz,1.0,female,1,1,0,3,1,0.0,fiber optic,...,0.0,1.0,1.0,0.0,month-to-month,1,mailed check,83.9,267.40,2.796667

In [ ]:
columnas_binarias = [
    'Abandono',
    'Teléfono_Múltiples_Líneas',
    'Internet_Protección_Dispositivo',
    'Internet_Soporte_Técnico',
    'Internet_Películas_Streaming'
]

for col in columnas_binarias:
    datosTelecom2[col] = datosTelecom2[col].astype('Int64')
datosTelecom2.head()

,ID_Cliente,Abandono,Género,Adulto_Mayor,Pareja,Dependientes,Antigüedad_Meses,Teléfono_Servicio,Teléfono_Múltiples_Líneas,Internet_Tipo_Servicio,...,Internet_Protección_Dispositivo,Internet_Soporte_Técnico,Internet_TV_Streaming,Internet_Películas_Streaming,Cuenta_Tipo_Contrato,Cuenta_Facturación_Sin_Papel,Cuenta_Método_Pago,Cuenta_Cargo_Mensual,Cuenta_Cargo_Total,Cuentas_Diarias
0,0002-orfbo,0,female,0,1,1,9,1,0,dsl,...,0,1,1.0,0,one year,1,mailed check,65.6,593.30,2.186667
1,0003-mknfe,0,male,0,0,0,9,1,1,dsl,...,0,0,0.0,1,month-to-month,0,mailed check,59.9,542.40,1.996667
2,0004-tlhlj,1,male,0,0,0,4,1,0,fiber optic,...,1,0,0.0,0,month-to-month,1,electronic check,73.9,280.85,2.463333
3,0011-igkff,1,male,1,1,0,13,1,0,fiber optic,...,1,0,1.0,1,month-to-month,1,electronic check,98.0,1237.85,3.266667
4,0013-exchz,1,female,1,1,0,3,1,0,fiber optic,...,0,1,1.0,0,month-to-month,1,mailed check,83.9,267.40,2.796667

### Eliminar Columnas no relevantes

In [ ]:
datosTelecom2 = datosTelecom2.drop(columns=["ID_Cliente"], errors="ignore")
datosTelecom2.head()

,Abandono,Género,Adulto_Mayor,Pareja,Dependientes,Antigüedad_Meses,Teléfono_Servicio,Teléfono_Múltiples_Líneas,Internet_Tipo_Servicio,Internet_Seguridad_En_Línea,...,Internet_Protección_Dispositivo,Internet_Soporte_Técnico,Internet_TV_Streaming,Internet_Películas_Streaming,Cuenta_Tipo_Contrato,Cuenta_Facturación_Sin_Papel,Cuenta_Método_Pago,Cuenta_Cargo_Mensual,Cuenta_Cargo_Total,Cuentas_Diarias
0,0,female,0,1,1,9,1,0,dsl,no,...,0,1,1.0,0,one year,1,mailed check,65.6,593.30,2.186667
1,0,male,0,0,0,9,1,1,dsl,no,...,0,0,0.0,1,month-to-month,0,mailed check,59.9,542.40,1.996667
2,1,male,0,0,0,4,1,0,fiber optic,no,...,1,0,0.0,0,month-to-month,1,electronic check,73.9,280.85,2.463333
3,1,male,1,1,0,13,1,0,fiber optic,no,...,1,0,1.0,1,month-to-month,1,electronic check,98.0,1237.85,3.266667
4,1,female,1,1,0,3,1,0,fiber optic,no,...,0,1,1.0,0,month-to-month,1,mailed check,83.9,267.40,2.796667

### Separar variable objetivo (Churn)

In [ ]:
datosTelecom2["Abandono"].value_counts()

Abandono
0    5174
1    1869
Name: count, dtype: Int64

In [ ]:
X = datosTelecom2.drop("Abandono", axis=1)
y = datosTelecom2["Abandono"]

In [ ]:
y.isnull().sum()

np.int64(224)

## Encoding
Convertimos variables categóricas en numéricas.

In [ ]:
X = pd.get_dummies(X, drop_first=True)

### Verificación de la Proporción de Cancelación (Churn)

In [ ]:
proporcion = y.value_counts(normalize=True)
print(proporcion)

Abandono
0    0.73463
1    0.26537
Name: proportion, dtype: Float64

In [ ]:
# En porcentaje para ver desvalance
print(y.value_counts(normalize=True) * 100)

Abandono
0    73.463013
1    26.536987
Name: proportion, dtype: Float64

## Balanceo de Clases

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:399: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)

ValueError: Input y contains NaN.

## Normalización o Estandarización (si es necesario)
Evalúa la necesidad de normalizar o estandarizar los datos, según los modelos que se aplicarán. Modelos basados en distancia, como KNN, SVM, Regresión Logística y Redes Neuronales, requieren este preprocesamiento. Por otro lado, modelos basados en árboles, como Decision Tree, Random Forest y XGBoost, no son sensibles a la escala de los datos.

In [ ]:
from sklearn.preprocessing import StandardScaler

escalar = StandardScaler()

X_escaledo = escalar.fit_transform(X)